/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FunJC                                                 *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmFunJC;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsFunJC[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalFunJC = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acFunJC[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_X__, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXX____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXX_, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XX______, _XXXXXXX, XXX_____, _____XX_, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, X_______, ____XXXX, XX_____X, __XX__XX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, __X__XXX, X___XXXX, XX_XXXXX, XXXXX__X, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XX_, _X______, XXXXXXXX, XXXXXXXX, _____XXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XX_, X_______, _____X__, ____X___, _X_____X, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX_XX_X, X_XXXX__, XX_X____, _X______, __XXXX__, XX___XXX, XXXXXXXX,
  XXXXXXXX, XXX_X__X, _XX_____, X_XXX_X_, XX___X_X, X__XX_XX, __X__XXX, XXXXXXXX,
  XXXXXXXX, XXX_X_XX, _X__XX_X, __X___X_, ______X_, XXX_XXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XX_XXXX_, XXX__X_X, __XXXXXX, X_XX_XXX, XX___XXX, XXXXXXXX,
  XXXXXXXX, XXX__X_X, XXXXXXXX, XXX_XX_X, X_XXXXXX, XXXXXXXX, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX_X_X, XXXXXXXX, XXXXX_XX, XXXXXXXX, XXXXXXXX, XX_XX_XX, XXXXXXXX,
  XXXXXXXX, XXX__X__, XXXXXXXX, XXX____X, X_XXXXXX, XXXXXXXX, XX_XX_XX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, XX___XX_, X_XXXXXX, XXXXXXXX, XX__X_XX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, X__XXXXX, XX_XXXXX, XXXXXXXX, XXX_X_XX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, __XX_XX_, _XXX_XXX, XXXXXXXX, XX_XX_XX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, __X__XXX, __XXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, XX_XXXXX, XX_XXXXX, XXXXXXXX, XXX_X_XX, XXXXXXXX,
  XXXXXXXX, XXX_XXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXXXXXX, _____XXX, XX____XX, XXXXXXXX, XXX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XX__XX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_X____X, XXXXXXXX, XXXXXXXX, X__XXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_XXXX__, _XXXXXXX, XXXXXX__, __XXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, ___XXXXX, XXX____X, XXXXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, X____XXX, X___XXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXX___, _XXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmFunJC = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acFunJC,  // Pointer to picture data (indices)
  &_PalFunJC   // Pointer to palette
};

/*************************** End of file ****************************/
