/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SunHR                                                 *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSunHR;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsSunHR[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalSunHR = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acSunHR[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX_X___, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, __XX____, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, __XXX___, ________, ________, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, _XXXXX__, ___X____, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _______X, XXXXXXXX, ___XX___, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ___X__XX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXX__, ___XXXXX, XXXXXX__, ___XXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXX__, ____XXXX, XXXX____, ____XXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXXX_, _____XXX, XX______, __X___XX, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX_X__, XXXXXXXX, XXX___XX, XX_____X, XXX__XXX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXX_XX__, XXXXXXXX, XXXX__XX, XX____XX, XXXXXXXX, __XX_XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, XXXXX___, ___XX_XX, XXX__X__, _XXXXXXX, _XXX_XXX, XXXXXXXX,
  XXXXXXXX, X_XX__X_, XXX____X, ____XXXX, XXXX____, _X__XXXX, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXX__, XXXXXXXX, XXXX_XX_, X____XXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XX_XXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __X_X_XX, XXXXXXXX,
  XXXXXXXX, XX_XXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXX_XX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX__XX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XX_XXX, XXXXXXXX,
  XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXXXXXXX, XXXX___X, X__XXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXXXX, XXX____X, ____XXXX, XXXXXXXX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXX_, ____XXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXX____, __XXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, X_______, ______XX, XXXXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, _____XX_, X_____XX, XXXXX_XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__XXXX, __XX__XX, XXXXX__X, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_XXXX, ______XX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXX__, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmSunHR = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acSunHR,  // Pointer to picture data (indices)
  &_PalSunHR   // Pointer to palette
};

/*************************** End of file ****************************/
